main_code/main_code/urls.py
from django.contrib import admin
from django.urls import path, include

app_name = "mainurls"

urlpatterns = [
    path('admin/', admin.site.urls, name="admin-page"),
    path('', include('webpage.urls')),
]

main_code/webpage/urls.py
# from unicodedata import name
from django.urls import path
from . import views
from .views import (aboutPage, detailEmployees, employeesPage, homePage, mainPage,register_time_employee)
from django.urls import path
from .views import CustomLoginView



app_name = "webpage"

urlpatterns = [
     path('login/', CustomLoginView.as_view(), name='login'),
    path('', mainPage, name='webpage-view'),
    path('entenda-melhor/', homePage, name='homepage-view'),
    path('sobre/', aboutPage, name='aboutpage-view'),
    path('colaborador/',employeesPage,name='employeespage-view'),
    path('colaborador-info/<int:id>', detailEmployees, name='employeeinfo-view'),
    path('registrando-horario/',register_time_employee,name='register_time_employee'),
    path('',views.aboutPage),
]

main_code/webpage/models.py
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db.models import (CharField, DateField, IntegerField, Model, ForeignKey, TimeField, RESTRICT, CASCADE)
from datetime import datetime, time


class Cargo(Model):
    cargo = CharField(max_length=50, blank=False, null=False)

    def __str__(self):
        return self.cargo

class Funcionario(Model):
    nome = CharField(max_length=32, blank=False, null=False)
    sobrenome = CharField(max_length=32, blank=False, null=False)
    admissão = DateField(blank=False, null=False)
    cargo = ForeignKey(Cargo, on_delete=RESTRICT, default="Sem_cargo_denifido", blank=True, null=True)
    idade = IntegerField(
        validators=[
            MaxValueValidator(100),
            MinValueValidator(10)
        ], blank=False, null=False
     )
    genero = CharField(max_length=30,choices=[
        ('Masculino','Masculino'),
        ('Feminino','Feminino'),
        ('NA','Prefiro não opinar')])
    aniversário = DateField()
    endereço = CharField(max_length=75, blank=True, null=True)
    CPF = IntegerField(blank=True, null=True)

    def __str__(self):
        return (f"{self.nome} {self.sobrenome}")

class CheckIn(Model):
    NOW = datetime.now
    funcionario = ForeignKey(Funcionario, on_delete=RESTRICT)
    dia = DateField(default=NOW)
    entrada_manha = TimeField(auto_now=False, auto_now_add=False, default=time(0,0), null=True,blank=True)
    saida_manha = TimeField(auto_now=False, auto_now_add=False, default=time(0,0), null=True,blank=True)
    entrada_tarde = TimeField(auto_now=False, auto_now_add=False, default=time(0,0), null=True,blank=True)
    saida_tarde = TimeField(auto_now=False, auto_now_add=False, default=time(0,0), null=True,blank=True)

    def __str__(self):
        return (f"{self.funcionario} - {self.dia}")

main_code/webpage/views.py
from django.urls import reverse
from django.http import HttpResponse
from .models import CheckIn, Funcionario
from django.core.paginator import Paginator
from datetime import datetime, time, timedelta
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib.auth.views import LoginView

class CustomLoginView(LoginView):
    template_name = 'login.html'

def mainPage(request):
    employees = Funcionario.objects.all()
    return render(request, 'index.html', {'employees':employees})

def homePage(request):
    return render(request, 'mainpage.html')

def aboutPage(request):
    return render(request, 'about.html')

def employeesPage(request):
    employees_list = Funcionario.objects.all().order_by('nome')
    paginator = Paginator(employees_list, 6)
    page = request.GET.get('page')
    employees = paginator.get_page(page)

    return render(request, 'employees.html', {'employees': employees})

def detailEmployees(request, id):
    # Solicita as informações do colaborador
    employee_info = get_object_or_404(Funcionario, pk=id)
    
    # Solicita e limita as informações do colaborador especificado
    checkin_list = CheckIn.objects.filter(funcionario=employee_info).order_by('-dia')
    paginator = Paginator(checkin_list, 32) # Tempo de carreira a ser mostrado
    page = request.GET.get('page')
    checkins = paginator.get_page(page)
    
    # Calcula o tempo de carreira do especificado na paginação
    horas_trabalhadas = sum((checkin.saida_manha.hour - checkin.entrada_manha.hour) + (checkin.saida_tarde.hour - checkin.entrada_tarde.hour) for checkin in checkin_list)
    minutos_trabalhadas = sum((checkin.saida_manha.minute - checkin.entrada_manha.minute) + (checkin.saida_tarde.minute - checkin.entrada_tarde.minute) for checkin in checkin_list)
    horas_totais_trabalhadas = timedelta(days=0,hours=horas_trabalhadas,minutes=minutos_trabalhadas)
    
    # Formata o tempo calculado para exibição
    horas_teste = str(horas_totais_trabalhadas)
    tempo_array = horas_teste.split(':')
    tempo_real = f"{tempo_array[0]} Horas e {tempo_array[1]} Minutos"

    return render(request, 'employees-info.html', {'employee_info': employee_info, 'checkins': checkins, 'horas_trabalhadas':tempo_real})

def register_time_employee(request,*args, **kwargs):
    funcionario = Funcionario.objects.get(id=request.POST.get('employees'))
    horario = request.POST.get('horario')
    horas = int(horario[0:2])
    minutos = int(horario[3:5])
        
    if request.POST.get('entrada-manha') is not None:
        checkin, criado = CheckIn.objects.get_or_create(funcionario=funcionario,dia=datetime.now())
        checkin.entrada_manha = time(hour=horas,minute=minutos)
        checkin.save()
    if request.POST.get('entrada-tarde') is not None:
        checkin, criado = CheckIn.objects.get_or_create(funcionario=funcionario,dia=datetime.now())
        checkin.entrada_tarde = time(hour=horas,minute=minutos)
        checkin.save()
    if request.POST.get('saida-manha') is not None:
        checkin, criado = CheckIn.objects.get_or_create(funcionario=funcionario,dia=datetime.now())
        checkin.saida_manha = time(hour=horas,minute=minutos)
        checkin.save()
    if request.POST.get('saida-tarde') is not None:
        checkin, criado = CheckIn.objects.get_or_create(funcionario=funcionario,dia=datetime.now())
        checkin.saida_tarde = time(hour=horas,minute=minutos)
        checkin.save()
        
    return redirect(reverse('webpage:webpage-view'))

main_code/webpage/templates/about.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Página Principal</title>

    <!-- CSS -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>

    <!-- Barra Lateral -->
    <aside class="sidebar">
        <header>
            <img src="{% static 'img/defaultlogo_small.png' %}" class="sidebar-img" alt="Seletos Lancamentos">
        </header>
        <ul class="siderbar-link-main">
            <li><a href="/admin/" class="sidebar-link" target="_blank" rel="noreferrer noopener">{% comment %}  {% endcomment %}
                <span class="sidebar-icon"><ion-icon name="person-circle-outline"></ion-icon></span>
                <span class="sidebar-text">Página de Admin</span>
            </a></li>
            <li><a href="{% url 'webpage:webpage-view' %}" class="sidebar-link">
                <span class="sidebar-icon"><ion-icon name="home-outline"></ion-icon></span>
                <span class="sidebar-text">Página Principal</span>
            </a></li>
            <li><a href="{% url 'webpage:homepage-view' %}" class="sidebar-link">
                <span class="sidebar-icon"><ion-icon name="help-buoy-outline"></ion-icon></ion-icon></span>
                <span class="sidebar-text">Entenda melhor</span>
            </a></li>
            <li><a href="{% url 'webpage:employeespage-view' %}" class="sidebar-link">{% comment %}  {% endcomment %}
                <span class="sidebar-icon"><ion-icon name="people-outline"></ion-icon></span>
                <span class="sidebar-text">Colaboradores</span>
            </a></li>
            <li><a href="{% url 'webpage:aboutpage-view' %}" class="sidebar-link">
                <span class="sidebar-icon"><ion-icon name="information-circle-outline"></ion-icon></ion-icon></span>
                <span class="sidebar-text">Sobre</span>
            </a></li>
        </ul>
    </aside>

    <!-- Conteúdo da página -->
    <main>
        <content>
            <h1 class="main-title">Sobre o sistema</h1>
            <p class="main-description">
                Este projeto foi idealizado inicialmente como um projeto de estudo, e conforme foi se desenvolvendo achei uma boa ideia<br>disponibilizar para o público, apesar de ser algo simples e bruto, nunca sabemos quem pode estar precisando de algo do tipo!<br>
                <br>
                Caso queira tirar alguma dúvida sobre o sistema, basta entrar em contato com
                <span><a href="https://github.com/Anthhon" target="_blank" rel="noreferrer noopener">Anthony Silva</a></span>
                ou
                <span><a href="https://github.com/Rip4568" target="_blank" rel="noreferrer noopener">Jonathas David.</a></span><br>
                <br>
                O sistema possui código aberto, então caso queira dar uma olhada e tirar alguma dúvida basta acessar
                <span><a href="https://github.com/Anthhon/sistema-de-ponto" target="_blank" rel="noreferrer noopener">este link.</a></span>
            </p>
        </content>
    </main>

    <!-- Others -->
    <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
    <script src="https://kit.fontawesome.com/yourcode.js" crossorigin="anonymous"></script>
</body>
</html>

main_code/webpage/templates/employees-info.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Página Principal</title>

    <!-- CSS -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

</head>
<body>

    <!-- Barra Lateral -->
    <aside class="sidebar">
        <header>
            <img src="{% static 'img/defaultlogo_small.png' %}" class="sidebar-img" alt="Seletos Lancamentos">
        </header>
        <ul class="siderbar-link-main">
            <li><a href="/admin/" class="sidebar-link" target="_blank" rel="noreferrer noopener">{% comment %}  {% endcomment %}
                <span class="sidebar-icon"><ion-icon name="person-circle-outline"></ion-icon></span>
                <span class="sidebar-text">Página de Admin</span>
            </a></li>
            <li><a href="{% url 'webpage:webpage-view' %}" class="sidebar-link">
                <span class="sidebar-icon"><ion-icon name="home-outline"></ion-icon></span>
                <span class="sidebar-text">Página Principal</span>
            </a></li>
            <li><a href="{% url 'webpage:homepage-view' %}" class="sidebar-link">
                <span class="sidebar-icon"><ion-icon name="help-buoy-outline"></ion-icon></ion-icon></span>
                <span class="sidebar-text">Entenda melhor</span>
            </a></li>
            <li><a href="{% url 'webpage:employeespage-view' %}" class="sidebar-link">{% comment %}  {% endcomment %}
                <span class="sidebar-icon"><ion-icon name="people-outline"></ion-icon></span>
                <span class="sidebar-text">Colaboradores</span>
            </a></li>
            <li><a href="{% url 'webpage:aboutpage-view' %}" class="sidebar-link">
                <span class="sidebar-icon"><ion-icon name="information-circle-outline"></ion-icon></ion-icon></span>
                <span class="sidebar-text">Sobre</span>
            </a></li>
        </ul>
    </aside>

    <!-- Conteúdo da página -->
    <main>
        <content>

            <!-- Descrição colaborador -->
            <h1 class="main-title">Colaborador</h1>
            <div class="desc-box">
                <content class="desc-row">
                    <p class="main-description">
                        <strong>Nome:</strong> {{ employee_info.nome }}
                    </p>
                    <p class="main-description">
                        <strong>Sobrenome:</strong> {{ employee_info.sobrenome }}
                    </p>
                    <p class="main-description">
                        <strong>Cargo:</strong> {{ employee_info.cargo }}
                    </p>
                    <p class="main-description">
                        <strong>Idade:</strong> {{ employee_info.idade }} anos
                    </p>
                    <p class="main-description">
                        <strong>Genero:</strong> {{ employee_info.genero }}
                    </p>
                </content>
                <content class="desc-row">
                    <p class="main-description">
                        <strong>Admissão:</strong> {{ employee_info.admissão }}
                    </p>
                    <p class="main-description">
                        <strong>Aniversário:</strong> {{ employee_info.aniversário }}
                    </p>
                </content>
                <content class="desc-row">
                    <p class="main-description">
                        <strong>Endereço:</strong> {{ employee_info.endereço }}
                    </p>
                </content>
                <content class="desc-row">
                    <p class="main-description">
                        <strong>CPF:</strong> {{ employee_info.CPF }}
                    </p>
                </content>
            </div>

            <!-- Histórico de horários -->
            <h1 class="main-title" id="main-title-historic"><ion-icon name="time-outline"></ion-icon>Histórico</h1>
            <p class="carreer-time">Horas trabalhadas: {{horas_trabalhadas}}</p>
            <div class="check-box">
                {% for checkin in checkins %}
                <content class="check-row">
                    <p class="main-check">
                        <ion-icon name="calendar-outline"></ion-icon> {{checkin.dia}}
                    </p>
                    <p class="main-check">
                        <strong>Manhã:</strong> {{checkin.entrada_manha}} - {{checkin.saida_manha}}
                    </p>
                    <p class="main-check">
                        <strong>Tarde:</strong> {{checkin.entrada_tarde}} - {{checkin.saida_tarde}}
                    </p>
                </content>
                {% endfor %}
            </div>
        </content>

        <!-- Rodapé  -->
        <footer class="footer-buttons">
            <span>
                <a href="/admin/webpage/funcionario/{{ employee_info.id }}/change/?_to_field=id" class="footer-links" target="_blank" rel="noreferrer noopener">Editar informações</a>
            </span>
        </footer>
    </main>

    <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
    <!-- Others -->
    <script src="https://kit.fontawesome.com/yourcode.js" crossorigin="anonymous"></script>
</body>
</html>

main_code/webpage/templates/employees.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Página Principal</title>

    <!-- CSS -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>

    <!-- Barra Lateral -->
    <aside class="sidebar">
        <header>
            <img src="{% static 'img/defaultlogo_small.png' %}" class="sidebar-img" alt="Seletos Lancamentos">
        </header>
        <ul class="siderbar-link-main">
            <li><a href="/admin/" class="sidebar-link" target="_blank" rel="noreferrer noopener">{% comment %}  {% endcomment %}
                <span class="sidebar-icon"><ion-icon name="person-circle-outline"></ion-icon></span>
                <span class="sidebar-text">Página de Admin</span>
            </a></li>
            <li><a href="{% url 'webpage:webpage-view' %}" class="sidebar-link">
                <span class="sidebar-icon"><ion-icon name="home-outline"></ion-icon></span>
                <span class="sidebar-text">Página Principal</span>
            </a></li>
            <li><a href="{% url 'webpage:homepage-view' %}" class="sidebar-link">
                <span class="sidebar-icon"><ion-icon name="help-buoy-outline"></ion-icon></ion-icon></span>
                <span class="sidebar-text">Entenda melhor</span>
            </a></li>
            <li><a href="{% url 'webpage:employeespage-view' %}" class="sidebar-link">{% comment %}  {% endcomment %}
                <span class="sidebar-icon"><ion-icon name="people-outline"></ion-icon></span>
                <span class="sidebar-text">Colaboradores</span>
            </a></li>
            <li><a href="{% url 'webpage:aboutpage-view' %}" class="sidebar-link">
                <span class="sidebar-icon"><ion-icon name="information-circle-outline"></ion-icon></ion-icon></span>
                <span class="sidebar-text">Sobre</span>
            </a></li>
        </ul>
    </aside>

    <!-- Botão de cada colaborador -->
    <main>

        <!--Texto descritivo -->
        <article>
            <h1 class="main-title">Colaboradores</h1>
            <p class="main-description">
                Logo abaixo estão sendo exibidos todos os colaboradores <strong>registrados no sistema</strong>, se não estiver vendo nada, significa que ninguém foi adicionado ainda!<br>
                <strong>Caso tenha certeza</strong> de que quer adicionar alguém ao sistema, basta
                <span><a href="/admin/webpage/funcionario/add/?_to_field=id" target="_blank" rel="noreferrer noopener">clicar aqui.</a></span>
            </p>
        </article>

        <!-- Funcionários -->
        {% for employee in employees %}
        <div class="employee-content">
            <a href="{% url 'webpage:employeeinfo-view' employee.pk %}" class="employee-box">
                <p class="employee-firstname">
                    <strong>{{employee.nome}}</strong>
                </p>
                <p class="employee-lastname">
                    <strong>{{employee.sobrenome}}</strong>
                </p>
                <p class="employee-job">
                    {{employee.cargo}}
                </p>
                <p class="employee-sex">
                    {{employee.genero}}
                </p>
            </a>
        </div>
        {% endfor %}

        <div class="pagination">
            <span class="step-links">
                {% if employees.has_previous %}
                    <a href="?page={{ employees.previous_page_number }}"><i class="step-link-icon"><ion-icon name="chevron-back-outline"></ion-icon></i></a>
                {% endif %}

                <span class="current-page">
                    Página {{ employees.number }} de {{ employees.paginator.num_pages }}
                </span>

                {% if employees.has_next %}
                    <a href="?page={{ employees.next_page_number }}"><i class="step-link-icon"><ion-icon name="chevron-forward-outline"></ion-icon></i></a>
                {% endif %}
            </span>
        </div>
    </main>

    <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
    <!-- Others -->
    <script src="https://kit.fontawesome.com/yourcode.js" crossorigin="anonymous"></script>
</body>
</html>

main_code/webpage/templates/index.html
{% load static %}

<!DOCTYPE html>

<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Página Principal</title>
    
    
    <!-- CSS -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body class="black-bg">
    
    <!-- Conteúdo da página -->
    <main class="pres-main">
        <content class="pres-content-div">
            
            <!-- Logo -->
            <img class="pres-img" src="{% static 'img/defaultlogo.png' %}" alt="Seletos Lancamentos Logo">

            <!-- Conteúdo -->
            <div class="main-content-div">

                <!-- Saudação -->
                <h3 class="pres-title">
                    <strong>Seja bem-vindo</strong> ao nosso<br>
                    sistema de ponto!
                </h3>
                
                <!-- Ponto eletrônico -->
                <div class="ep-box">
                    
                    <form action="{% url 'webpage:register_time_employee' %}" method='post'>
                        {% csrf_token %}

                        <!-- Horário -->
                        <span class="pres-input-span">
                            <input type="time" id="horario" name="horario" min="5" max="5" placeholder="Digite um horário" class="pres-input" required>
                        </span>

                        <!-- Funcionário -->
                        <select name="employees" id="employees">
                            {% for employee in employees %}
                            <option value="{{ employee.pk }}">{{ employee.nome }} {{ employee.sobrenome }}</option>
                            {% endfor %}
                        </select>

                            <!-- Botões -->
                        <div class="buttons-main-div">
                            <p>Manhã</p>
                            <span class="button-row">
                                    <input type="submit" name="entrada-manha" value="Entrada">
                                    <input type="submit" name="saida-manha" value="Saida">
                            </span>
                            <p>Tarde</p>
                            <span class="button-row">
                                    <input type="submit" name="entrada-tarde" value="Entrada">
                                    <input type="submit" name="saida-tarde" value="Saída">
                            </span>
                        </div>
                    </form>
                    
                    

                    
                </div>

                <!-- Veja mais -->
                <a href="{% url 'webpage:homepage-view' %}" class="pres-link">
                    <span class="pres-text">Veja mais</span>
                </a>
            </div>
        </content>
    </main>
    <script>
document.addEventListener('DOMContentLoaded', () => {
    const form = document.querySelector('form'); // Seleciona o formulário
    const empresaLat = -22.162563; // Latitude da empresa
    const empresaLng = -51.425709; // Longitude da empresa
    const radius = 0.01; // Raio de verificação em km

    function toRadians(degrees) {
        return degrees * (Math.PI / 180);
    }

    function haversineDistance(lat1, lng1, lat2, lng2) {
        const R = 6371; // Raio da Terra em km
        const dLat = toRadians(lat2 - lat1);
        const dLng = toRadians(lng2 - lng1);
        const a = Math.sin(dLat / 2) ** 2 +
                  Math.cos(toRadians(lat1)) * Math.cos(toRadians(lat2)) * 
                  Math.sin(dLng / 2) ** 2;
        const c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
        return R * c; // Distância em km
    }

    function checkLocation(event) {
        if (navigator.geolocation) {
            navigator.geolocation.getCurrentPosition(position => {
                const { latitude, longitude } = position.coords;
                const distance = haversineDistance(latitude, longitude, empresaLat, empresaLng);

                console.log('Latitude:', latitude);
                console.log('Longitude:', longitude);
                console.log('Distance:', distance);

                if (distance > radius) {
                    event.preventDefault(); // Previne o envio do formulário se não estiver dentro da área
                    alert('Você precisa estar dentro da empresa para registrar o ponto.');
                }
                // Se estiver dentro do raio, o formulário será enviado normalmente
            }, (error) => {
                console.error('Erro ao obter a localização:', error);
                alert('Não foi possível obter sua localização.');
                event.preventDefault(); // Previne o envio do formulário em caso de erro de localização
            });
        } else {
            alert('Geolocalização não é suportada pelo seu navegador.');
            event.preventDefault(); // Previne o envio do formulário se geolocalização não for suportada
        }
    }

    form.addEventListener('submit', checkLocation);
});
    </script>
    
    <!-- Others -->
    <script src="https://kit.fontawesome.com/yourcode.js" crossorigin="anonymous"></script>
</body>
</html>

main_code/webpage/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body class="black-bg">
    <div class="login-container">
        <h2>Login</h2>
        <form method="post">
            {% csrf_token %}
            <div>
                <label for="username">Usuário:</label>
                <input type="text" id="username" name="username" required>
            </div>
            <div>
                <label for="password">Senha:</label>
                <input type="password" id="password" name="password" required>
            </div>
            <div>
                <button type="submit">Entrar</button>
            </div>
        </form>
    </div>
</body>
</html>

main_code/webpage/templates/mainpage.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Página Principal</title>

    <!-- CSS -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

</head>
<body>

    <!-- Barra Lateral -->
    <aside class="sidebar">
        <header>
            <img src="{% static 'img/defaultlogo_small.png' %}" class="sidebar-img" alt="Seletos Lancamentos">
        </header>
        <ul class="siderbar-link-main">
            <li><a href="/admin/" class="sidebar-link" target="_blank" rel="noreferrer noopener">{% comment %}  {% endcomment %}
                <span class="sidebar-icon"><ion-icon name="person-circle-outline"></ion-icon></span>
                <span class="sidebar-text">Página de Admin</span>
            </a></li>
            <li><a href="{% url 'webpage:webpage-view' %}" class="sidebar-link">
                <span class="sidebar-icon"><ion-icon name="home-outline"></ion-icon></span>
                <span class="sidebar-text">Página Principal</span>
            </a></li>
            <li><a href="{% url 'webpage:homepage-view' %}" class="sidebar-link">
                <span class="sidebar-icon"><ion-icon name="help-buoy-outline"></ion-icon></ion-icon></span>
                <span class="sidebar-text">Entenda melhor</span>
            </a></li>
            <li><a href="{% url 'webpage:employeespage-view' %}" class="sidebar-link">
                <span class="sidebar-icon"><ion-icon name="people-outline"></ion-icon></span>
                <span class="sidebar-text">Colaboradores</span>
            </a></li>
            <li><a href="{% url 'webpage:aboutpage-view' %}" class="sidebar-link">
                <span class="sidebar-icon"><ion-icon name="information-circle-outline"></ion-icon></ion-icon></span>
                <span class="sidebar-text">Sobre</span>
            </a></li>
        </ul>
    </aside>

    <!-- Conteúdo da página -->
    <main>
        <content>
            <h1 class="main-title">Página Principal</h1>
            <p class="main-description">
                Esse sistema foi feito no intuito de ajudar pequenas e médias empresas<br>
                a <strong>melhor gerenciarem os horários de seus funcionarios de maneira simples e fácil.</strong><br>
                <br>
                Para registrar os horários de entrada e saída de um colaborador é bem simples!<br>
                Basta escrever o horário no campo especificado e selecionar o botão de acordo com o desejado. 
            </p>
        </content>
        <content>
            <h1 class="main-subtitle">Colaboradores</h1>
            <p class="main-description">
                Na aba de colaboradores é possível ver uma <strong>lista completa com todos as pessoas que foram adicionados ao sistema.</strong><br>
                <br>
                Todos os colaboradores são organizados por ordem alfabética de modo a facilitar a busca, encontrando a pessoa desejada<br>
                <strong>basta apenas selecionar a caixa de texto correspondente e será exibido uma tela com todas as informações cadastradas sobre a mesma</strong>,<br>
                além disso, logo abaixo também é possível encontrar o histórico de horários de entrada e saída do mesmo.<br>
                <br>
                Caso conste alguma <strong>informação errada no sistema</strong> basta procurar pelo botão de "Editar informações" abaixo do histórico de horário<br>
                e mudar as informações na página de administrador
            </p>
        </content>
        <content>
            <h1 class="main-subtitle">Sobre</h1>
            <p class="main-description">
                Caso deseje saber mais informações técnicas sobre o sistema ou <strong>se comunicar com os responsáveis sobre o sistema</strong> basta consultar esta aba! 
            </p>
        </content>
    </main>

    <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
    <!-- Others -->
    <script src="https://kit.fontawesome.com/yourcode.js" crossorigin="anonymous"></script>
</body>
</html>